__title__ = 'htk'
__description__ = 'A set of convenience utils for Python'
__url__ = 'https://github.com/hacktoolkit/python-htk'
__version__ = '2.0.1'
__author__ = 'Hacktoolkit'
__author_email__ = 'hello@hacktoolkit.com'
__license__ = 'MIT'
__copyright__ = 'Copyright 2023 Hacktoolkit'
